clickhouse:
  host: "10.81.0.136"
  write_hosts:
    - "10.25.78.163"
    - "10.25.78.164"
  port: 9000
  database: "feedgen"
  user: "feedgen"
  password: "dien9ux9aithohbec0aephu5meYee4In"

job:
  interval_hours: 6.0
  retry_attempts: 3
  retry_delay_seconds: 60

