nats:
  url: "nats://localhost:4222"
  subject: "ch.write.raw"
  durable: "ch_writer"

clickhouse:
  host: "10.81.0.136"
  port: 9000
  database: "feedgen"
  user: "feedgen"
  password: "dien9ux9aithohbec0aephu5meYee4In"

batch:
  size: 25000
  interval_sec: 5.0
  max_buffer_size: 200000
