ab_client:
  url: "http://10.25.78.131/common_ipban"
  interval: 60.0
  timeout: 10

nats:
  url: "nats://localhost:4222"
  dg_consumer:
    subject: "dg.load.command"
    durable: "dg_consumer"
  pa_consumer:
    subject: "dg.pa.request"

parser:
  clickhouse_dt_format: "%Y-%m-%d %H:%M:%S"

pa_request:
  max_period_days: 7
